import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.scss";

const tajawal = Tajawal({
  weight: ["300", "500", "700"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App | Hisham",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={tajawal.className}>{children}</body>
    </html>
  );
}
